### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ringabout** [ringabout/Nim#26]
- [x] fixes oids
- [x] fixes findstr
- [ ] mimalloc
- [x] threads system
- [x] nimslimsystem
- [x] templates with type inference https://github.com/nim-lang/Nim/commit/0014b9c48e883d3c04995b9e83bb0f8468a16df6 https://github.com/nim-lang/Nim/pull/20505 
- [x] regression https://github.com/nim-lang/Nim/issues/20450
- [x] objectconstr regarding default fields
- [x] replace ast pattern matching links
- [x] take over google font loading
- [ ] https://github.com/nim-lang/Nim/issues/20139
- [x] refactor lexer strongSpaceA, strongSpaceB
- [ ] fixes cast[cstring](ptr char) in vm
- [x] documentation of default fields
- [x] fixes the remaining first node of object construction and add an assertion. We can handle it in the semTypeNode of the first node. The passed node should be a symbol node. We assemble a type node based on its type.

**Comment by ringabout** [comment]
- [ ] remove symbolfiles
